### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by Shirikatsu** [clearmatics/erc1820-registry#4]
What I did:
I created a new account as in http://127.0.0.1:8000/users/creating-an-account.html
founded the address and then tried to deploy an ERC1820 registry using that account
Finally, when I tried to deploy a contract I got the following warnings:

``` bash
docker run --rm -v "$(pwd)"/rpc-cert:/etc/ssl/certs -v "$(pwd)"/truffle-config.js:/app/truffle-config.js --network="host" -t clearmatics/erc1820-registry:v0.0.2 deploy -- --f 2 --describe-json
```

> erc1820-registry@0.0.1 deploy /app
> truffle deploy --network development "--f" "2" "--describe-json"
Compiling your contracts...
===========================
> Compiling ./contracts/ERC1820ImplementerInterface.sol
> Compiling ./contracts/ExampleImplementer.sol
> Compilation warnings encountered:
    /app/contracts/ExampleImplementer.sol:7:46: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function canImplementInterfaceForAddress(bytes32 interfaceHash, address addr) external view returns(bytes32) {
                                             ^-------------------^
,/app/contracts/ExampleImplementer.sol:7:69: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function canImplementInterfaceForAddress(bytes32 interfaceHash, address addr) external view returns(bytes32) {
                                                                    ^----------^
,/app/contracts/TestERC165.sol:48:29: Warning: "this" used in constructor. Note that external functions of a contract cannot be called while it is being constructed.
        supportedInterfaces[this.supportsInterface.selector] = true;
                            ^--^
,/app/contracts/TestERC165.sol:64:29: Warning: "this" used in constructor. Note that external functions of a contract cannot be called while it is being constructed.
        supportedInterfaces[this.is2D.selector ^ this.skinColor.selector] = true;
                            ^--^
,/app/contracts/TestERC165.sol:64:50: Warning: "this" used in constructor. Note that external functions of a contract cannot be called while it is being constructed.
        supportedInterfaces[this.is2D.selector ^ this.skinColor.selector] = true;
                                                 ^--^
> Artifacts written to /app/build/contracts
> Compiled successfully using:
   - solc: 0.5.3+commit.10d17f24.Emscripten.clang
MIGRATION_STATUS:{"status":"preAllMigrations","data":{"dryRun":false,"migrations":[{"file":"/app/migrations/2_erc1830_registry.js","number":2,"isFirst":true,"isLast":true,"dryRun":false,"interactive":false}]}}
Starting migrations...
======================
> Network name:    'development'
> Network id:      444900
> Block gas limit: 100000000 (0x5f5e100)
MIGRATION_STATUS:{"status":"preMigrate","data":{"file":"2_erc1830_registry.js","number":2,"isFirst":true,"network":"development","networkId":444900,"blockLimit":"0x5f5e100"}}
2_erc1830_registry.js
=====================
MIGRATION_STATUS:{"status":"deploying","data":{"contractName":"ERC1820Registry"}}
   Deploying 'ERC1820Registry'
   ---------------------------
   > transaction hash:    0x6e970d542490b497f350a5a93eaefcfb18ea1646e79a44388db82ca7a4c0bc38
   > Blocks: 0            Seconds: 0
   > contract address:    0x5b158Bd6Fa42e09cE5327dc3624A1015621Ea992
   > block number:        2697890
   > block timestamp:     1600265944
   > account:             0xfF783f414b21C987E8d08107Aa2c19E39275bb82
   > balance:             989.89375
   > gas used:            1010625 (0xf6bc1)
   > gas price:           10000 gwei
   > value sent:          0 ETH
   > total cost:          10.10625 ETH
MIGRATION_STATUS:{"status":"deployed","data":{"contract":{"contractName":"ERC1820Registry","address":"0x5b158Bd6Fa42e09cE5327dc3624A1015621Ea992"},"deployed":true,"receipt":{"transactionHash":"0x6e970d542490b497f350a5a93eaefcfb18ea1646e79a44388db82ca7a4c0bc38","gasUsed":1010625},"timestamp":1600265944,"gasPrice":"10000","gas":"1010625","from":"0xfF783f414b21C987E8d08107Aa2c19E39275bb82","value":"0","cost":"10.10625","balance":"989.89375"}}
   > Saving artifacts
   -------------------------------------
   > Total cost:            10.10625 ETH
MIGRATION_STATUS:{"status":"postMigrate","data":{"number":2,"cost":"10.10625"}}
Summary
=======
> Total deployments:   1
> Final cost:          10.10625 ETH
https://support.clearmatics.com/helpdesk/tickets/222

**Comment by Andreadinenno** [comment]
Fortunately this warnings are related to example contracts that are not even gonna be deployed.
Unfortunately Truffle doesn't provide a way to directly ignore or select the list of contracts to compile.

We can fix that immediately by adding flag `--quiet` to `truffle compile` that will silence warnings.

Other solutions would involve changing contracts folder structure and code: 
1. By moving the examples out of contracts folder. 
2. By fixing the warnings on the code

Suggestions? @cmjc

**Comment by cmjc** [comment]
I think it is better to not just silence warning but address the cause.

1. This seems the simplest solution - code remains in the repo, it is just not pulled in. E.g. moved to a `test-contracts` or appropriately named folder.
2. Not sure what `fixing the warnings` means - how would you change code to fix it?
